config/routes.rb
Rails.application.routes.draw do
  resources :events
  root 'events#index'
  devise_for :users

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    require_login
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :location, :details, :organiser)
    end

    def require_login
      unless user_signed_in?
        flash[:error] ="You must be logged in to add Links"
        redirect_to new_user_session_path # halts request cycle
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.label :organiser %><br>
    <%= f.text_field :organiser %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="container">
  <div class="starter-template">
    <h1>Upcoming events</h1>
    <% if flash[:error]%>
  <div class="alert alert-success" role="alert"><%= flash[:error] %></div>
<% end %>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
        </tr>
      </thead>
    </table>

    <% @events.each do |event|%>

    <div class="container">
     <div class="row">
      <div class="col-md-6"><%=event.title%></div>
       <div class="col-md-1"><%= link_to 'Show',event_path(event),class:"btn btn-default" %> </div>
       <div class="col-md-3">
        <%=event.location%>

      </div>
    </div>
    <hr>

  </div>
   <% end %>
 </div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Details:</strong>
  <%= @event.details %>
</p>

<p>
  <strong>Organiser:</strong>
  <%= @event.organiser %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-default" role="navigate">
 <div class="navbar-inner">
  <div class="container">
    <div id="logo" class="navbar-brand"><%= link_to "Event", root_path %></div>
      <nav class="collapse navbar-collapse navbar-ex1-collapse">
      <% if user_signed_in? %>
       <ul class="nav navbar-nav navbar-right">
         <li><%= link_to 'Submit Event', new_event_path %></li>
         <li><%= link_to 'Account Settings', edit_user_registration_path %></li>
         <li><%= link_to "Sign out", destroy_user_session_path, method: :DELETE %></li>
 </ul>

<% else %>

    <ul class="nav navbar-nav pull-right">
      <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <li><%= link_to 'Sign in', new_user_session_path %></li>
    </ul>
<% end %>
</nav>
</div>
</div>
</header>


<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="../../assets/javascripts/bootstrap.min.js"></script>
</body>
</html>